### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by JoungheeKim** [soyoung97/Standard_Korean_GEC#1]
안녕하세요.
좋은 코드와 실험을 공유해 주셔서 감사합니다.
매우 흥미롭게 살펴보고 있습니다.

제가 궁금한건 해당 코드에 대한 라이선스 입니다.
데이터는 별도의 라이선스가 있는거 같은데..
만드신 코드에 대한 라이선스도 혹시 알려주실 수 있을까요??

가능하시다면 깃에 라이선스도 업로드 해 주시면 좋을 것 같습니다.
감사합니다.

좋은 하루 되세요

**Comment by soyoung97** [comment]
Thanks for the suggestion (And your interest in our work)! We missed adding the code license. We will update the code LICENSE at README.md and at every code!
