### ISSUE TITLE
hi, could you send me the training data?

### ISSUE THREAD

**Issue by bitallin** [soyoung97/Standard_Korean_GEC#2]
i can't get the data.
here is my email:  ligen1@miduchina.com, thank you!

**Comment by soyoung97** [comment]
Hello!
Thanks for the interest in our work!!
Actually, the README file is a written in a bit messy way, so you may not have found it, but it's explained[ here,](https://github.com/soyoung97/Standard_Korean_GEC#kor-learner-and-kor-native) that you need to sign in[ this contract form](https://forms.gle/kF9pvJbLGvnh8ZnQ6) to get full access data. Once you submit the form, I will check my email about the submission and manually send the link to the google drive(Where datasets are stored).

If you have any other misleading instructions or questions, please contact me!

**Comment by soyoung97** [comment]
hi @bitallin , closing this issue; please send me the contract form and I'll e-mail with the data right away!
contract form: https://forms.gle/kF9pvJbLGvnh8ZnQ6
