### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'.                                                                                                                 

### ISSUE THREAD

**Issue by andreaschari** [soyoung97/Standard_Korean_GEC#4]
With the current `requirements.txt` I'm getting `AttributeError: module 'numpy' has no attribute 'bool'.` on python 3.8

Following this `https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool`
I upgraded numpy to `1.23.5` and the sample code works correctly now.
Maybe `numpy` needs to be added to the requirements to get the correct version?

**Comment by soyoung97** [comment]
Hi @andreaschari, thank you for the correction! I'll update the requirements.txt file.

Thanks again :)

Best,
Soyoung Yoon
